#!/bin/bash

# Este script é executado por: yadm bootstrap

ln -sf ~/.yadm/exclude ~/.yadm/repo.git/info/exclude

# tema principal
if [ -d ~/.zprezto ]; then
  cd ~/.zprezto
  git pull --rebase --stat origin master
  git submodule update --init --recursive
  cd -
else
  git clone --depth 1 --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
fi

# plugins adicionais
if [ -d ~/.oh-my-zsh ]; then
  cd ~/.oh-my-zsh
  git pull --rebase --stat origin master
  cd -
else
  git clone --depth 1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

# Universal version manager
if [ ! -d ~/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.1
fi

# zplug para gerenciar plugins
if [ ! -d ~/.zplug ]; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi
